security:
  user:
    password: password
spring:
  session:
    store-type: redis
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: example
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#      jdbc.lob.non_contextual_creation: true
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers:
