#spring:
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: example
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#      jdbc.lob.non_contextual_creation: true

security:
  user:
    password: password
  oauth2:
    client:
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
      client-id: acme
      client-secret: acmesecret
    resource:
      user-info-uri: http://localhost:9999/uaa/user

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
